name: Build & Test

on:
  schedule:
        - cron: "49 2 * * 1"
  workflow_dispatch:

jobs:
  test-matrix:
    if: ${{ !(github.event.pull_request.draft || false) }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift-version: ["6.0", "5.10", "5.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: ${{ matrix.swift-version }}
      - name: Get swift version
        run: swift --version
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v
