name: Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      license_header_check_project_name: "swift-libp2p"

  tests:
    name: Linux
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      enable_windows_checks: false

  test-matrix:
    name: MacOS
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        swift-version: ["6.0", "5.10", "5.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: ${{ matrix.swift-version }}
      - name: Get swift version
        run: swift --version
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v
