name: Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  tests:
    name: Pull Request
    uses: swift-libp2p/github-workflows/.github/workflows/pull_request.yml@main
